'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Html5QrcodeScanner } from 'html5-qrcode';
import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';

export default function ScanPage() {
  const router = useRouter();
  const [scanResult, setScanResult] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // Initialize scanner
    const scanner = new Html5QrcodeScanner(
      "reader",
      { 
        fps: 10, 
        qrbox: { width: 250, height: 250 },
        aspectRatio: 1.0
      },
      /* verbose= */ false
    );

    scanner.render(onScanSuccess, onScanFailure);

    function onScanSuccess(decodedText: string, decodedResult: any) {
      // Handle the scanned code
      console.log(`Scan result: ${decodedText}`, decodedResult);
      setScanResult(decodedText);
      
      // Stop scanning
      scanner.clear();

      // Check if it's a valid internal URL
      if (decodedText.includes('/apiaries/') || decodedText.includes('/hives/')) {
        // Extract the path if it's a full URL
        try {
          const url = new URL(decodedText);
          router.push(url.pathname);
        } catch (e) {
          // If it's relative or just a path
          router.push(decodedText);
        }
      } else {
        // If it's just an ID (e.g. "BG-001"), we might need to search for it.
        // For now, let's assume QR codes are URLs as generated by the app.
        setError('Ukjent QR-kode format. Vennligst skann en gyldig LEK-Biens Vokter kode.');
      }
    }

    function onScanFailure(error: any) {
      // handle scan failure, usually better to ignore and keep scanning.
      // console.warn(`Code scan error = ${error}`);
    }

    return () => {
      scanner.clear().catch(error => {
        console.error("Failed to clear html5-qrcode scanner. ", error);
      });
    };
  }, [router]);

  return (
    <div className="min-h-screen bg-black text-white flex flex-col">
      <header className="p-4 flex items-center gap-4 bg-black/50 backdrop-blur-sm fixed top-0 w-full z-10">
        <Link href="/dashboard" className="p-2 -ml-2 hover:bg-white/10 rounded-full">
          <ArrowLeft className="w-6 h-6" />
        </Link>
        <h1 className="text-xl font-bold">Skann QR-kode</h1>
      </header>

      <main className="flex-1 flex flex-col items-center justify-center p-4 mt-16">
        <div id="reader" className="w-full max-w-sm overflow-hidden rounded-xl border-2 border-honey-500 shadow-2xl bg-black"></div>
        
        {scanResult && (
          <div className="mt-8 p-4 bg-white text-black rounded-xl max-w-sm w-full text-center animate-in slide-in-from-bottom-4">
            <p className="text-sm text-gray-500 mb-1">Fant kode:</p>
            <p className="font-mono font-bold break-all">{scanResult}</p>
            <p className="text-xs text-gray-400 mt-2">Videresender...</p>
          </div>
        )}

        {error && (
          <div className="mt-8 p-4 bg-red-100 text-red-800 rounded-xl max-w-sm w-full text-center animate-in slide-in-from-bottom-4">
            <p className="font-bold mb-1">Feil</p>
            <p className="text-sm">{error}</p>
            <button 
              onClick={() => window.location.reload()}
              className="mt-4 px-4 py-2 bg-red-200 hover:bg-red-300 rounded-lg text-sm font-bold transition-colors"
            >
              Prøv igjen
            </button>
          </div>
        )}

        <div className="mt-12 text-center text-gray-400 text-sm max-w-xs">
          <p>Pek kameraet mot en QR-kode på en bikube eller bigård for å åpne den direkte.</p>
        </div>
      </main>
    </div>
  );
}
