export const PRODUCT_IMAGES = {
    HONEY_SUMMER: '/BILDER/2FF2EF66-C1D5-4309-AFFE-CE447D901FFA.png',
    HONEY_HEATHER: 'https://images.unsplash.com/photo-1589739900266-4399f579d5bf?w=800&q=80',
    SOAP: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=800&q=80',
    BEESWAX: 'https://images.unsplash.com/photo-1626202378964-340944f3e68e?w=800&q=80',
    COMB: 'https://images.unsplash.com/photo-1555447405-bd6145d279cf?w=800&q=80',
    HONEYCOMB: '/BILDER/612A0805-7459-41E4-A37F-24672786BC0D.png',
    HONEYCOMB_FRAME: '/BILDER/D6B86142-B83B-4592-8B1C-73396E595DE2.png',
    GIFT_BROWN: '/BILDER/F540572D-6909-4756-8C9E-E7C8FC465DF8.png',
    GIFT_BLACK_LARGE: '/BILDER/449D79D6-A20B-4B22-B328-D9BB5544BD3A.png',
    GIFT_WHITE_STACK: '/BILDER/0DF4E1BA-71EA-41F8-8C7E-9FF8E1A8A947.png',
    GIFT_BLACK_FLAT: '/BILDER/49E86A27-AA55-4D06-A4CE-D02BE63DBA4F.png',
    FALLBACK: '/BILDER/2FF2EF66-C1D5-4309-AFFE-CE447D901FFA.png',
};

export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'Sommerhonning',
    price: 149,
    category: 'Honning',
    image_url: PRODUCT_IMAGES.HONEY_SUMMER,
    description: 'Deilig, lys sommerhonning fra lokale bigårder. Mild og fin smak.',
    rating: 4.8,
    stock: 10,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: '2',
    name: 'Gavepakke "Biens Beste"',
    price: 499,
    category: 'Gavepakker',
    image_url: PRODUCT_IMAGES.GIFT_BROWN,
    description: 'En flott gaveeske med honning, såpe og et bivokslys.',
    rating: 5.0,
    stock: 8,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: '3',
    name: 'Gavepakke "Eksklusiv Svart"',
    price: 699,
    category: 'Gavepakker',
    image_url: PRODUCT_IMAGES.GIFT_BLACK_LARGE,
    description: 'Vår mest eksklusive gavepakke i stilig svart utførelse.',
    rating: 5.0,
    stock: 5,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: '4',
    name: 'Gavepakke "Tårnet"',
    price: 549,
    category: 'Gavepakker',
    image_url: PRODUCT_IMAGES.GIFT_WHITE_STACK,
    description: 'Et tårn av smaker! Tre glass honning og såpe i en elegant hvit gaveeske.',
    rating: 4.9,
    stock: 12,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: '5',
    name: 'Gavepakke "Duo Svart"',
    price: 349,
    category: 'Gavepakker',
    image_url: PRODUCT_IMAGES.GIFT_BLACK_FLAT,
    description: 'En lekker svart gaveeske med to utvalgte honningglass.',
    rating: 4.8,
    stock: 20,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: '6',
    name: 'Tavlehonning',
    price: 450,
    category: 'Honning',
    image_url: PRODUCT_IMAGES.HONEYCOMB,
    description: 'Deilig tavlehonning servert i en rustikk trekasse. Ekte vare rett fra bikuben.',
    rating: 4.9,
    stock: 5,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: '7',
    name: 'Tavlehonning (Hel tavle)',
    price: 480,
    category: 'Honning',
    image_url: PRODUCT_IMAGES.HONEYCOMB_FRAME,
    description: 'Hel tavle med honning. Pris er basert på ca 1 kg (450,-/kg) + ramme (30,-). Endelig pris justeres etter vekt.',
    rating: 5.0,
    stock: 5,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: '8',
    name: 'Håndlaget Bivoks-såpe',
    price: 89,
    category: 'Såpe',
    image_url: PRODUCT_IMAGES.SOAP,
    description: 'Naturlig såpe laget med bivoks og honning. Skånsom for huden.',
    rating: 4.7,
    stock: 20,
    is_active: true,
    created_at: new Date().toISOString()
  },
];
